### ISSUE TITLE
TypeError: subnet.split is not a function when used with Google subnets

### ISSUE THREAD

**Issue by rugk** [natesilva/is-in-subnet#21]
## Problem

I try running this and checking an IP on all [Google IP ranges](https://support.google.com/a/answer/10026322?hl=en) both in legacy IP (IPv4) and IPv6.
However, the `createChecker` step already seems to fail.

## Code

```js
const googleServiceIpApi = 'https://www.gstatic.com/ipranges/goog.json';
const googleCloudIpApi = 'https://www.gstatic.com/ipranges/cloud.json'; // TODO: use too

const ipv4Prefixes = [];
const ipv6Prefixes = [];

let ipv4Checker = null;
let ipv6Checker = null;

/**
 * Fetch the latest Google IP ranges.
 */
async function fetchIpRanges() {
    await fetch(googleServiceIpApi).then(response => {
        if (!response.ok) {
            console.error(`Error when fetching "${googleServiceIpApi}":`, response);
            return;
        }

        return response.json();
    }).then(jsonResponse => {
        ipv4Prefixes.push(jsonResponse.prefixes
            .filter(x => x.ipv4Prefix)
            .map(x => x.ipv4Prefix)
        );

        ipv6Prefixes.push(
            jsonResponse.prefixes
                .filter(x => x.ipv6Prefix)
                .map(x => x.ipv6Prefix)
        );

        console.info("IPv4 addresses found:", ipv4Prefixes);
        console.info("IPv6 addresses found:", ipv6Prefixes);

        ipv4Checker = isInSubnet.createChecker(ipv4Prefixes);
        ipv6Checker = isInSubnet.createChecker(ipv6Prefixes);
    });
}
```

## Stacktrace

```
 Uncaught (in promise) TypeError: subnet.split is not a function
    subnetsByVersion index.ts:33
    createChecker$2 index.ts:31
```

## System

Firefox 103.0.2
using the non-minified browser version
v4.0.1
(I'm developing a WebExtension, but that should not matter here.)

**Comment by rugk** [comment]
Ahh without a CORS circumvention you cannot load the URLs from gstatic. Well the simplest thing to reproduce is to include the JSON in the JS.

So did that here in this fiddle now and I can reproduce it with Firefox and Chromium:
https://jsfiddle.net/65ga3rzv/

## Firefox stacktrace from fiddle

```
Uncaught (in promise) TypeError: subnet.split is not a function
    subnetsByVersion index.ts:33
    createChecker$2 index.ts:31
    fetchIpRanges (index):317
    promise callback*fetchIpRanges (index):302
    <anonymous> (index):322
index.ts:33:24
    subnetsByVersion index.ts:33
    reduce self-hosted:217
    createChecker$2 index.ts:31
    fetchIpRanges (index):317
    (Async: promise callback)
    fetchIpRanges (index):302
    <anonym> (index):322
```

## Chromium stacktrace from fiddle

Chromium v104.0.5112.102

```
index.ts:33 Uncaught (in promise) TypeError: subnet.split is not a function
    at subnetOrSubnets.reduce.0 (index.ts:33:25)
    at Array.reduce (<anonymous>)
    at Object.createChecker$2 [as createChecker] (index.ts:31:44)
    at ?editor_console=:317:34
subnetOrSubnets.reduce.0 @ index.ts:33
createChecker$2 @ index.ts:31
(anonymous) @ ?editor_console=:317
Promise.then (async)
fetchIpRanges @ ?editor_console=:302
(anonymous) @ ?editor_console=:322
```

**Comment by rugk** [comment]
Oh damit I'm stupid. The input format is wrong of course.

I used ` Array.prototype.push` wrongly to push all elements into an array and of course it could not handle this. This is correct:
```js
        ipv4Prefixes = jsonResponse.prefixes
            .filter(x => x.ipv4Prefix)
            .map(x => x.ipv4Prefix);

        ipv6Prefixes = jsonResponse.prefixes
            .filter(x => x.ipv6Prefix)
            .flatMap(x => x.ipv6Prefix);
```
